### PR TITLE
Replace all 'parent' with 'main'

### PR DESCRIPTION
**Pull request by tmf97**
### Summary

This PR solves a confusion issue. A lot of objects take in the `MainSatelliteThread` object as a `parent` in order to access other parts of FSW, but there is no inherent parent-child relationship in any of these uses. This PR renames all relevent `parent` objects gets renamed it `main`.

### Testing

Existing unit tests

### Notes

We do have a circular dependency for most of the objects that take in a `MainSatelliteThread` object, which is pointing to an architectural issue that we should resolve. I have some ideas on this I'd like to discuss eventually. 

### Comments
- [ ] Add an x between the brackets if you commented your code well!

### CODE REVIEW

**Review by sjz38 — APPROVED** [review]
👍Can confirm all instance of `parent` have been changed to `main`

**Review by RohitValiveti — APPROVED** [review]
Confirmed all instances of parent were removed via Find in Files (cmd+shift+f)

**Comment by sjz38** [comment]
@RohitValiveti Note that not all code reviews are this easy 🤣

**Comment by tmf97** [comment]
Gotta start somewhere!

**Comment by RohitValiveti** [comment]
Got my expectations high with this one 😅

**Pull request merged**
