### PR TITLE
Detection accuracy truth test

### PR DESCRIPTION
**Pull request by sjz38**
### Summary

This PR addresses Jira ticket CISLUNAR- 51    
Adds testing capabilities to our find algorithm based on the presence of earth, moon and sun. Provides accuracy metrics on the number of misclassifications and total accuracy.

### Testing

This branch adds a test for the find algorithm which provides us with accuracy metrics for our find algorithm. Truth values are hand-generated by looking at each image in the dataset and marking the presence of earth, moon and sun in a csv.

### Notes

Currently, our find_with_contours misclassifies the sun once in case1c. We may want to look into why this is happening. I also tried making path differences easier to manage. There are only two paths that are needed to be changed, which are at the top of the test file.

### Comments
- [x] Add an x between the brackets if you commented your code well!
- @adamrnasir  and @andxu282 , please take a look at this and try running it yourself! Let me know of any feedback.

### CODE REVIEW

**Review by adamrnasir — APPROVED** [review]
Looks good to me, small typo on line 50 of test_detections.py.

I like the modularization of file paths/directories, which promotes ease of use for all devs.

**Review by andxu282 — APPROVED** [review]
Testing script looks good, will look more into why that one case is failing.

**Comment by tmf97** [comment]
The CI tests that are failing are flight software related and not caused by any of your code changes. I'm pretty sure these tests will pass once we get the latest version of flight software into the opnav branches. I'd say we're good to merge

**Comment by sjz38** [comment]
Thanks for the feedback. I also added an assert so that if the accuracy falls below a certain threshold (90% in this case) the test will fail. This will be helpful in the future when testing other find implementations

**Pull request merged**
